name: Create Draft Release

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"

jobs:

  build:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rumps==0.4.0
        pip install py2app==0.28.6
        pip install feedparser==6.0.10
        brew update
        brew install create-dmg
    - name: Build Application
      run: |
        python setup.py py2app
    - name: Build dmg installer
      run: |
        mkdir -p dist/dmg
        cp -r "dist/MergeRequestsMonitor.app" dist/dmg
        create-dmg --volname "MergeRequestsMonitor" --volicon "media/icon.png" --window-pos 200 120 --window-size 600 300 --icon-size 100 --icon "MergeRequestsMonitor.app" 175 120 --hide-extension "MergeRequestsMonitor.app" --app-drop-link 425 120 "dist/MergeRequestsMonitor-${{ github.ref_name }}.dmg" "dist/dmg/"
    - name: Generate App.zip
      run: |
        cd dist && zip -r MergeRequestsMonitor-${{ github.ref_name }}.zip MergeRequestsMonitor.app
    - uses: ncipollo/release-action@v1
      with:
        draft: true
        allowUpdates: true
        generateReleaseNotes: true
        artifacts: "dist/MergeRequestsMonitor-${{ github.ref_name }}.zip,dist/MergeRequestsMonitor-${{ github.ref_name }}.dmg"
